### ISSUE TITLE
All elements in a feature must contain the full details provided by the section of the parser that obtains them

### ISSUE THREAD

**Issue by alistair-broomhead** [london-python-project-nights/romaine#37]
So I was looking to demo where we were up to with Romaine, and wrote the following test script

```
from romaine.core import Core
from romaine.steps import Given, When, Then


def define_test_steps():

    @Given("I have a test framework")
    def i_have_a_test_framework():
        pass

    @When("I pass")
    def i_pass():
        pass

    @When("I fail")
    def i_fail():
        assert False

    @Then("everything's fine")
    def everything_is_fine():
        pass

    @Then("this step isn't run")
    def this_is_not_run():
        pass


FEATURE_LINES = [
    "Feature: Test framework",
    " As a conscientious developer",
    " I want to test my code",
    "",
    "  Scenario: Everything passes",
    "   Given I have a test framework",
    "    When I pass",
    "    Then everything's fine",
    "",
    "  Scenario: Something fails",
    "   Given I have a test framework",
    "    When I fail",
    "    Then this step isn't run",
]

if __name__ == "__main__":
    core = Core()
    feature_parser = core.Parser().feature
    feature = feature_parser.get_feature(FEATURE_LINES)["feature"]
    define_test_steps()

    core.run_features(feature)
```

So this script is executed as expected, but the output is not as expected.

```
$ python demo.py 
Feature: Test framework
 As a conscientious developer
 I want to test my code

Scenario: Everything passes
Given I have a test framework
Step 'Given I have a test framework' executed in 8e-06 seconds
When I pass
Step 'When I pass' executed in 9e-06 seconds
Then everything's fine
Step "Then everything's fine" executed in 7e-06 seconds
Scenario 'Everything passes' executed in 0.00048 seconds
Scenario: Something fails
Given I have a test framework
Step 'Given I have a test framework' executed in 7e-06 seconds
When I fail
Step 'When I fail' executed in 0.000161 seconds
Scenario 'Something fails' executed in 0.000421 seconds
Feature: Test framework executed in 0.001229 seconds

Traceback (most recent call last):
  File "/home/al/git/romaine/src/romaine/core.py", line 57, in run_features
    runner.run_feature(feature, self.steps, logger)
  File "/home/al/git/romaine/src/romaine/runner.py", line 4, in run_feature
    run_scenario(scenario, steps, logger)
  File "/home/al/git/romaine/src/romaine/runner.py", line 15, in run_scenario
    run_step(step, steps, logger, step_type)
  File "/home/al/git/romaine/src/romaine/runner.py", line 63, in run_step
    definition.func(*args, **kwargs)
  File "demo.py", line 17, in i_fail
    assert False
AssertionError
1 feature (0 passed)
2 scenarios (1 passed)
6 steps (1 failed, 4 passed)
All tests executed in 0.00148 seconds
```

Obviously the runner is not complete and there are logging issues to be fixed in the fact that the `Then` step is not displayed, but when I debugged the issue I found that there were two things leading to the indentation not being correctly displayed.
1. The logger code does not look for whitespace
2. The feature itself doesn't contain any leading or trailing whitespace

Unfortunately while `1.` has an obvious fix, it relies on `2.`. There are a few options for `2.` which is compounded by the loosely defined nature of gherkin, I might be tempted to not include leading and trailing whitespace, but actually preserve the full raw lines of the scenario heading/steps

**Comment by geokala** [comment]
I was going to say- for the logging just output the raw lines. You can output the parsed form in some situations (e.g. when there are issues "I found a <thing> which had <stuff>, but that's not right").

**Comment by alistair-broomhead** [comment]
Then we'll have to update the parser to give the raw output, currently this is the feature object:

```
{
    'stats': {
        'skipped_steps': 0,
        'failed': False,
        'total_steps': 0,
        'duration': None,
        'passed_scenarios': 0,
        'failed_scenarios': 0,
        'failed_steps': 0,
        'total_scenarios': 0,
        'passed': False,
        'passed_steps': 0
    },
    'leading_space_and_comments': [],
    'header': ['Feature: Test framework', ' As a conscientious developer', ' I want to test my code', ''],
    'background': None,
    'trailing_space_and_comments': [],
    'tags': [],
    'elements': [{
        'description': ' Everything passes',
        'steps': [{
            'multiline_arg': None,
            'text': 'I have a test framework',
            'trailing_whitespace': [],
            'leading_comments_and_space': [],
            'stats': {
                'duration': None,
                'passed': False,
                'skipped': False,
                'failed': False
            },
            'type': 'Given'
        }, {
            'trailing_whitespace': [],
            'leading_comments_and_space': [],
            'text': 'I pass',
            'multiline_arg': None,
            'type': 'When'
        }, {
            'trailing_whitespace': [''],
            'leading_comments_and_space': [],
            'text': "everything's fine",
            'multiline_arg': None,
            'type': 'Then'
        }],
        'leading_comments_and_space': [],
        'stats': {
            'skipped_steps': 0,
            'failed': False,
            'total_steps': 0,
            'failed_steps': 0,
            'passed': False,
            'duration': None,
            'passed_steps': 0
        },
        'tags': [],
        'type': 'scenario'
    }, {
        'description': ' Something fails',
        'leading_comments_and_space': [],
        'steps': [{
            'trailing_whitespace': [],
            'leading_comments_and_space': [],
            'text': 'I have a test framework',
            'multiline_arg': None,
            'type': 'Given'
        }, {
            'trailing_whitespace': [],
            'leading_comments_and_space': [],
            'text': 'I fail',
            'multiline_arg': None,
            'type': 'When'
        }, {
            'trailing_whitespace': [],
            'leading_comments_and_space': [],
            'text': "this step isn't run",
            'multiline_arg': None,
            'type': 'Then'
        }],
        'tags': [],
        'type': 'scenario'
    }]
}
```

**Comment by geokala** [comment]
That doesn't look right. all of the parser multiline+ (i.e. not the
simple ones) components should be returning a raw_input as well- the
base of any object returned should contain it.
Hmm...
Unless...
Ah- yeah, so the feature itself should have raw_input at the top level-
its top level keys should be: remaining (remaining lines), raw_input
(the raw input), and feature (the feature found, if any).

**Comment by alistair-broomhead** [comment]
Ah, so because we need to print output in-between, we need the raw_input and leading/trailing for each element

**Comment by geokala** [comment]
Makes sense. Do you want to edit this issue description to be "All elements in a feature must contain the full details provided by the section of the parser that obtains them" or something like that?

**Comment by geokala** [comment]
Just started working on this, should have a PR in the next day or two.

**Comment by geokala** [comment]
I've been modifying the expected output, but I'm not sure I'm going the right way at the moment (might just be because I've got my head full of json).

So, currently the feature output starts with:

``` json
{
  "feature": {
    "header": [
      "Feature: Basic SMTP server",
      "  In order to successfully use an SMTP server it must listen on port 25.",
      "  If it does not do this then most SMTP servers will have difficulty",
      "  delivering mail to this server.",
      ""
    ],
    "tags": [
      "smtp",
      "base"
    ],
```

Do you think it actually wants to start with:

``` json
{
  "feature": {
    "header": {
        "header": [
          "Feature: Basic SMTP server",
          "  In order to successfully use an SMTP server it must listen on port 25.",
          "  If it does not do this then most SMTP servers will have difficulty",
          "  delivering mail to this server.",
          ""
       ],
      "remaining": [ ...<SNIP>... ],
      "raw_input":[ ...<SNIP>... ]
    },
    "tags": {
      "tags": [
        "smtp",
        "base"
      ],
      "remaining": [ ...<SNIP>... ],
      "raw_input": [ ...<SNIP>... ]
    },
```

It feels a little clumsy ( ['tags']['tags'] ), but does give the full required output, and in a simple (code-wise) way, by simply taking the results from each parser call and dumping them under each section.

Thoughts?

**Comment by geokala** [comment]
PR includes changes as discussed on Wednesday.
